services:
  sfdc-middleware:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sfdc-middleware
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - ./salesforce_data.db:/app/salesforce_data.db
      - ./app.db:/app/app.db
